### ISSUE TITLE
compile error when I upgraded to latest EPICS base 7.0.8.1

### ISSUE THREAD

**Issue by LeeYangLBLBCS** [paulscherrerinstitute/ADZMQ#6]
````

I had to upgrade the epics base for other reason, then I am getting this compile error with ADZ module:



make -C ./zmqIOC install
make[2]: Entering directory '/opt/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADZMQ/iocs/zmqIOC'
make -C ./configure install
make[3]: Entering directory '/opt/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADZMQ/iocs/zmqIOC/configure'
make -C O.linux-x86_64 -f ../Makefile TOP=../.. \
    T_A=linux-x86_64 install
make[4]: Entering directory '/opt/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADZMQ/iocs/zmqIOC/configure/O.linux-x86_64'
perl -CSD /opt/epics/base/bin/linux-x86_64/convertRelease.pl checkRelease
make[4]: Leaving directory '/opt/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADZMQ/iocs/zmqIOC/configure/O.linux-x86_64'
make[3]: Leaving directory '/opt/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADZMQ/iocs/zmqIOC/configure'
make -C ./zmqApp install
make[3]: Entering directory '/opt/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADZMQ/iocs/zmqIOC/zmqApp'
make -C ./src install
make[4]: Entering directory '/opt/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADZMQ/iocs/zmqIOC/zmqApp/src'
make -C O.linux-x86_64 -f ../Makefile TOP=../../.. \
    T_A=linux-x86_64 install
make[5]: Entering directory '/opt/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADZMQ/iocs/zmqIOC/zmqApp/src/O.linux-x86_64'
/usr/bin/g++ -o zmqApp  -L/opt/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADZMQ/lib/linux-x86_64 -L/opt/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADZMQ/iocs/zmqIOC/lib/linux-x86_64 -L/opt/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADCore/lib/linux-x86_64 -L/opt/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADSupport/lib/linux-x86_64 -L/opt/epics/modules/synApps_6_1_epics7/support/asyn-R4-45/lib/linux-x86_64 -L/opt/epics/modules/synApps_6_1_epics7/support/autosave-R5-10/lib/linux-x86_64 -L/opt/epics/modules/synApps_6_1_epics7/support/busy-R1-7-2/lib/linux-x86_64 -L/opt/epics/modules/synApps_6_1_epics7/support/calc-R3-7-4/lib/linux-x86_64 -L/opt/epics/modules/synApps_6_1_epics7/support/iocStats-3-1-16/lib/linux-x86_64 -L/opt/epics/modules/synApps_6_1_epics7/support/seq-2-2-9/lib/linux-x86_64 -L/opt/epics/modules/synApps_6_1_epics7/support/sscan-R2-11-3/lib/linux-x86_64 -L/opt/epics/base/lib/linux-x86_64 -Wl,-rpath,/opt/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADZMQ/lib/linux-x86_64 -Wl,-rpath,/opt/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADZMQ/iocs/zmqIOC/lib/linux-x86_64 -Wl,-rpath,/opt/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADCore/lib/linux-x86_64 -Wl,-rpath,/opt/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADSupport/lib/linux-x86_64 -Wl,-rpath,/opt/epics/modules/synApps_6_1_epics7/support/asyn-R4-45/lib/linux-x86_64 -Wl,-rpath,/opt/epics/modules/synApps_6_1_epics7/support/autosave-R5-10/lib/linux-x86_64 -Wl,-rpath,/opt/epics/modules/synApps_6_1_epics7/support/busy-R1-7-2/lib/linux-x86_64 -Wl,-rpath,/opt/epics/modules/synApps_6_1_epics7/support/calc-R3-7-4/lib/linux-x86_64 -Wl,-rpath,/opt/epics/modules/synApps_6_1_epics7/support/iocStats-3-1-16/lib/linux-x86_64 -Wl,-rpath,/opt/epics/modules/synApps_6_1_epics7/support/seq-2-2-9/lib/linux-x86_64 -Wl,-rpath,/opt/epics/modules/synApps_6_1_epics7/support/sscan-R2-11-3/lib/linux-x86_64 -Wl,-rpath,/opt/epics/base/lib/linux-x86_64          -rdynamic -m64         zmqApp_registerRecordDeviceDriver.o zmqAppMain.o    -lADZMQ -lzmq -lNDPlugin -lADBase -lntndArrayConverter -lnt -lpvDatabase -lpvAccessIOC -lpvAccessCA -lpvAccess -lpvData -lnetCDF -lMagick++ -lcoders -lMagick -ljbig -ljp2 -lbzlib -lpng -lwebp -llcms -lttf -lwmf -lfilters -lnanohttp_stream -ltiff -lxml2 -lNeXus -lhdf5 -lhdf5_hl -lbitshuffle -lblosc -lszip -lzlib -ljpeg -lasyn -lautosave -lbusy -lcalc -ldevIocStats -lsscan -lseq -lpv -ldbRecStd -ldbCore -lca -lCom  -lX11 -lXext 
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADZMQ/lib/linux-x86_64/libADZMQ.so: undefined reference to `non-virtual thunk to NDPluginDriver::run()'
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/busy-R1-7-2/lib/linux-x86_64/libbusy.so: undefined reference to `asynPortDriver::doCallbacksInt8Array(char*, unsigned long, int, int)'
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/busy-R1-7-2/lib/linux-x86_64/libbusy.so: undefined reference to `asynPortDriver::readInt8Array(asynUser*, char*, unsigned long, unsigned long*)'
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/busy-R1-7-2/lib/linux-x86_64/libbusy.so: undefined reference to `asynPortDriver::writeInt8Array(asynUser*, char*, unsigned long)'
collect2: error: ld returned 1 exit status
make[5]: *** [/opt/epics/base/configure/RULES_BUILD:231: zmqApp] Error 1
make[5]: Leaving directory '/opt/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADZMQ/iocs/zmqIOC/zmqApp/src/O.linux-x86_64'
make[4]: *** [/opt/epics/base/configure/RULES_ARCHS:58: install.linux-x86_64] Error 2
make[4]: Leaving directory '/opt/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADZMQ/iocs/zmqIOC/zmqApp/src'
make[3]: *** [/opt/epics/base/configure/RULES_DIRS:85: src.install] Error 2
make[3]: Leaving directory '/opt/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADZMQ/iocs/zmqIOC/zmqApp'
make[2]: *** [/opt/epics/base/configure/RULES_DIRS:85: zmqApp.install] Error 2
make[2]: Leaving directory '/opt/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADZMQ/iocs/zmqIOC'
make[1]: *** [/opt/epics/base/configure/RULES_DIRS:85: zmqIOC.install] Error 2
make[1]: Leaving directory '/opt/epics/modules/synApps_6_1_epics7/support/areaDetector-R3-7/ADZMQ/iocs'
make: *** [/opt/epics/base/configure/RULES_DIRS:85: iocs.install] Error 2


At first, I thought it was because I was using the older asyn-R4-44-2, so I upgraded to asyn-R4-45

Both asyn versions failed with the same error.

This used to compile with EPICS base 7.0.4.

Do you know what might be the problem?

**Comment by LeeYangLBLBCS** [comment]
I figured out the error I had was caused by previous compilation result.
It went away after I did a "make distclean".
